### PR TITLE
add Page Views

### PR DESCRIPTION
**Pull request by xdvrx1**
When we add this service, it will count every hit of this repo. And this will guide us more about the visitors each day and will indicate the total views. For me, this is very helpful both for us and for those will view this repo seeing this page views.

Screenshot (1632)

### CODE REVIEW

**Comment by fisforfaheem** [comment]
tired of useless notification fot his *** app

**Comment by xdvrx1** [comment]
@fisforfaheem, you are not even a contributor to this repo, how come? I think you don't have the right to say that.

**Comment by fisforfaheem** [comment]
i subscribed to it.. but all i see is some useless bunch of replies etc
notifications so  now i am dfiableig them,,,, sorry for offnese ..but no
ioffense

**Comment by HouariZegai** [comment]
I don't think it will be an added value to the project

**Pull request closed without merging**
